descending order based on date
benchopt/benchOpt pull request #209
Opened 2021-09-14 17:25 UTC by agramfort

for some reason this does not work

help welcome @tanglef 

basically I want to see the latest results appear first

2021-09-14 18:47 UTC, tanglef requested changes
To do that, we actually need to touch the JS in `benchmark.mako.html`.
I will do a PR on your branch with the changes needed

2021-09-14 18:47 UTC, tanglef commented on benchopt/plotting/generate_html.py
> +        fnames = sorted(set(fnames))[::-1]
The elements are not sorted here but in the JS table because of jquery/aria anyway, so this can be removed

2021-09-15 08:35 UTC, agramfort commented
can you have a look?

we try to push these days the final touches to benchopt to push a new
release
that should be the first stable release.

thx !

>

2021-09-15 08:49 UTC, tanglef commented
I can't push directly on your branch so I made a PR (https://github.com/agramfort/benchOpt/pull/1) on your forked version of the repo. If that is ok for you, you can merge it on your branch and it will be all good here.

2021-09-15 09:13 UTC, tanglef commented
And the CI seem to be good today :)

2021-09-15 09:14 UTC, agramfort commented
works like a charm @tanglef  thx heaps !

2021-09-15 09:47 UTC, merged