Multiple level calls in html generation CLI
benchopt/benchopt pull request #231
Opened 2021-11-05 14:11 UTC by tanglef

Fixes #230 by allowing users to call `generate-results` from multiple levels.
For example:

benchmarks
├─ benchmark_lasso <- we're inside here
├─ benchmark_logreg_l1

you can do `benchopt generate-results -b . -b ../benchmark_logreg_l1` and get a menu page with each benchmark which will not lead to 404 error page (poke @mathurinm).

2021-11-05 17:51 UTC, agramfort commented
@mathurinm merge if you're happy

2021-11-06 08:16 UTC, tomMoral requested changes
Thanks a lot for the proposed fix. But I think we should change this function to rely on the `Benchmark` object so we avoid accessing folders manually. This requires a bit more changes, I can do it if you don't have time.

2021-11-17 08:39 UTC, tanglef commented
So, I didn't respond to take time to understand what the task really would mean using `Benchmark`, and I'm not sure I totally get it.
You would want to use said `Benchmark` object in a common framework for local and the website renderings, but the `results` repository is not made of `Benchmarks`, only folders with csv files  (no `objective.py`, ...) so I'll turn this PR into draft for now and try and work on it when I have the time

2021-11-17 16:01 UTC, tomMoral commented
Ok I see what you mean now. I would proceed that way:

- add an optional argument in `Benchmark` to not check that `objective.py` exists so you can still create the `Benchmark` object in `results`
- Use a list of `Benchmark` in both cases with `get_results_files` to list all files.

We might want to update a bit the `publish` command to also select the folder name from `get_output_folder`.

2021-12-24 11:48 UTC, tanglef commented
- [x] optional argument `standalone` in `Benchmark` to use a Benchmark even if no `objective.py` file exist
- [x] use a list of `Benchmark` (without `get_results_files` because of the pattern arg) using `benchmark.benchmark_dir` as anchor
- [ ] take into account possible duplicates results (cf #263, but how as there is possibly no `objective.py` target id -whatever we choose it to be- to match with ?)  
- [ ] update the publish command

2023-05-10 11:31 UTC, tanglef commented
The command `benchopt generate-results -b .` works with current changes and I think the `publish` and multiple repo names problem should be addresses in another PR with more discussion (out of the current scope)

2023-05-16 12:29 UTC, tanglef commented
@tomMoral if it's good for you, it's good for me. I updated with recent modifications. And all checks are good now

2023-07-04 14:03 UTC, mathurinm commented on benchopt/benchmark.py
> +            function for the benchmark.
@tanglef can you document the `standalone` parameter?

2023-07-06 13:08 UTC, mathurinm commented on benchopt/benchmark.py
> +            `standalone=True` in order to visualize available results.
@tomMoral it's the `click` parameter right?

2023-09-07 08:27 UTC, tanglef commented
Conflicts with `main` solved

2023-09-07 09:02 UTC, mathurinm approved these changes

2023-09-07 11:07 UTC, merged

2023-09-07 14:09 UTC, tomMoral commented
I don't think this is correct, what is the difference between standalone and `allow_meta_from_json`?

Sorry I feel like I reimplemented a bit the same logic on the meta data (I worked on this in the context of the plotting config, I did not realize it was similar).

But I am not sure it makes sense to have both?

2023-09-07 14:23 UTC, tanglef commented
> I don't think this is correct, what is the difference between standalone and `allow_meta_from_json`?
> 
> Sorry I feel like I reimplemented a bit the same logic on the meta data (I worked on this in the context of the plotting config, I did not realize it was similar).
> 
> But I am not sure it makes sense to have both?

Sorry, I didn't follow this feature release. I just tested it out and the multiple level calls works with `allow_meta_from_json`, just have to remove this part in `benchmark.py` and replacethe `standalone=True` with your `allow_meta_from_json=True`.
Should I do this in another PR ?

2023-09-08 06:50 UTC, tomMoral commented
no worries, sorry I did a second implementation instead of merging this one.

a follow up PR would be nice yes