FIX APGD implementation
benchopt/benchOpt pull request #61
Opened 2020-09-11 11:45 UTC by mathurinm

Comparison of the 2 implems:
![image](https://user-images.githubusercontent.com/8993218/92921759-f2f76e00-f434-11ea-8644-3ff98485379e.png)

closes #60

2020-09-11 12:48 UTC, agramfort approved these changes

2020-09-11 17:22 UTC, TomDLT requested changes
That explains the poor performances of the old APGD on the Boston dataset:
![Figure_1](https://user-images.githubusercontent.com/11065596/92954557-7c4c7780-f418-11ea-94ee-ce9ffc168bb1.png)
However, your fix diverges:
![Figure_1b](https://user-images.githubusercontent.com/11065596/92954582-853d4900-f418-11ea-983a-2c05dc497051.png)
This is because the gradient step should be taken from the auxiliary variable. With my proposed fix:
![Figure_2](https://user-images.githubusercontent.com/11065596/92954491-6343c680-f418-11ea-8d7d-1eb3f4aad42b.png)

2020-09-11 17:22 UTC, TomDLT commented on benchmarks/lasso/solvers/python_pgd.py
> +            w -= self.X.T @ (self.X @ z - self.y) / L
```suggestion
            w = z - self.X.T @ (self.X @ z - self.y) / L
```

2020-09-11 18:55 UTC, mathurinm commented
Thanks for the thorough review !
It is still weird that pgd outperforms apgd on Boston, don't you think ?

Le ven. 11 sept. 2020 à 19:22, Tom Dupré la Tour <notifications@github.com>
a écrit :

> *@TomDLT* requested changes on this pull request.
>
> That explains the poor performances of the old APGD on the Boston dataset:
> [image: Figure_1]
> <https://user-images.githubusercontent.com/11065596/92954557-7c4c7780-f418-11ea-94ee-ce9ffc168bb1.png>
> However, your fix diverges:
> [image: Figure_1b]
> <https://user-images.githubusercontent.com/11065596/92954582-853d4900-f418-11ea-983a-2c05dc497051.png>
> This is because the gradient step should be taken from the auxiliary
> variable. With my proposed fix:
> [image: Figure_2]
> <https://user-images.githubusercontent.com/11065596/92954491-6343c680-f418-11ea-8d7d-1eb3f4aad42b.png>
> ------------------------------
>
> In benchmarks/lasso/solvers/python_pgd.py
> <https://github.com/benchopt/benchOpt/pull/61#discussion_r487181348>:
>
> >          t_new = 1
>
>          for _ in range(n_iter):
>
>              if self.use_acceleration:
>
>                  t_old = t_new
>
>                  t_new = (1 + np.sqrt(1 + 4 * t_old ** 2)) / 2
>
>                  w_old = w.copy()
>
> -            grad = self.X.T.dot(self.X.dot(w) - self.y)
>
> -            w -= grad / L
>
> +            else:
>
> +                z = w
>
> +            w -= self.X.T @ (self.X @ z - self.y) / L
>
>
> ⬇️ Suggested change
>
> -            w -= self.X.T @ (self.X @ z - self.y) / L
>
> +            w = z - self.X.T @ (self.X @ z - self.y) / L
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/benchopt/benchOpt/pull/61#pullrequestreview-486984234>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACETTQQZPJX7MPBOFCFEPITSFJMFJANCNFSM4RHJNLHA>
> .
>

2020-09-11 20:13 UTC, TomDLT commented
Rerunning the benchmark with 100 repetitions.
![Figure_1](https://user-images.githubusercontent.com/11065596/92968602-4ca96980-f430-11ea-916e-1d975dbecdf8.png)
![Figure_2](https://user-images.githubusercontent.com/11065596/92968609-4d420000-f430-11ea-85f8-a896effc0c40.png)
![Figure_3](https://user-images.githubusercontent.com/11065596/92968610-4dda9680-f430-11ea-82dd-140dab35a84b.png)

2020-09-12 09:12 UTC, agramfort commented
I also get now some:

|----Python-PGD[use_acceleration=False]: done (did not converge)
|----Python-PGD[use_acceleration=True]: done (did not converge)

on simulated or boston.

it seems we have a regression here.

2020-09-13 15:45 UTC, agramfort approved these changes
@TomDLT I changed a bit more to avoid an extra copy for PDG without accel.

2020-09-13 15:45 UTC, agramfort commented
and forget about my brain fart about regression above. I was using -n instead of -r ...

all good on my side

2020-09-14 15:43 UTC, TomDLT approved these changes

2020-09-15 04:51 UTC, tomMoral approved these changes

2020-09-15 04:52 UTC, merged

2020-09-15 04:52 UTC, tomMoral commented
Thanks everyone!